# config/segmentation_dataset.yaml
path: datasets/segmentation  # dataset root
train: images/train
val: images/val
test: images/test

# Segmentation with single class 'panel' (class 0)
names: ['panel']
nc: 1
# For ultralytics segmentation you will provide masks alongside images in same filename under masks/
